//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassiopeia.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cassiopeia.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string año {
            get {
                return ResourceManager.GetString("año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string artista {
            get {
                return ResourceManager.GetString("artista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        public static string canciones {
            get {
                return ResourceManager.GetString("canciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total duration.
        /// </summary>
        public static string dur_total {
            get {
                return ResourceManager.GetString("dur_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string duracion {
            get {
                return ResourceManager.GetString("duracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string genero {
            get {
                return ResourceManager.GetString("genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Metal.
        /// </summary>
        public static string genero_blackmetal {
            get {
                return ResourceManager.GetString("genero_blackmetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blues rock.
        /// </summary>
        public static string genero_blues {
            get {
                return ResourceManager.GetString("genero_blues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiptune.
        /// </summary>
        public static string genero_chiptune {
            get {
                return ResourceManager.GetString("genero_chiptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical music.
        /// </summary>
        public static string genero_clasica {
            get {
                return ResourceManager.GetString("genero_clasica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disco.
        /// </summary>
        public static string genero_disco {
            get {
                return ResourceManager.GetString("genero_disco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronical music.
        /// </summary>
        public static string genero_electronica {
            get {
                return ResourceManager.GetString("genero_electronica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flamenco.
        /// </summary>
        public static string genero_flamenquito {
            get {
                return ResourceManager.GetString("genero_flamenquito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folk.
        /// </summary>
        public static string genero_folk {
            get {
                return ResourceManager.GetString("genero_folk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funk.
        /// </summary>
        public static string genero_funk {
            get {
                return ResourceManager.GetString("genero_funk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard rock.
        /// </summary>
        public static string genero_hardrock {
            get {
                return ResourceManager.GetString("genero_hardrock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy metal.
        /// </summary>
        public static string genero_heavymetal {
            get {
                return ResourceManager.GetString("genero_heavymetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indie rock.
        /// </summary>
        public static string genero_indierock {
            get {
                return ResourceManager.GetString("genero_indierock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz.
        /// </summary>
        public static string genero_jazz {
            get {
                return ResourceManager.GetString("genero_jazz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazz fusion.
        /// </summary>
        public static string genero_jazz_fusion {
            get {
                return ResourceManager.GetString("genero_jazz fusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New wave.
        /// </summary>
        public static string genero_new_wave {
            get {
                return ResourceManager.GetString("genero_new wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop.
        /// </summary>
        public static string genero_pop {
            get {
                return ResourceManager.GetString("genero_pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-punk.
        /// </summary>
        public static string genero_postpunk {
            get {
                return ResourceManager.GetString("genero_postpunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-rock.
        /// </summary>
        public static string genero_postrock {
            get {
                return ResourceManager.GetString("genero_postrock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive metal.
        /// </summary>
        public static string genero_progmetal {
            get {
                return ResourceManager.GetString("genero_progmetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punk.
        /// </summary>
        public static string genero_punk {
            get {
                return ResourceManager.GetString("genero_punk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progressive rock.
        /// </summary>
        public static string genero_rockprog {
            get {
                return ResourceManager.GetString("genero_rockprog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Psychedellic rock.
        /// </summary>
        public static string genero_rockpsicodelico {
            get {
                return ResourceManager.GetString("genero_rockpsicodelico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symphonic Rock.
        /// </summary>
        public static string genero_rocksinfonico {
            get {
                return ResourceManager.GetString("genero_rocksinfonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ska.
        /// </summary>
        public static string genero_ska {
            get {
                return ResourceManager.GetString("genero_ska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoner.
        /// </summary>
        public static string genero_stoner {
            get {
                return ResourceManager.GetString("genero_stoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoner rock/metal.
        /// </summary>
        public static string genero_vaporwave {
            get {
                return ResourceManager.GetString("genero_vaporwave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string menu_archivo {
            get {
                return ResourceManager.GetString("menu_archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
    }
}
