//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cassiopeia.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cassiopeia.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About Cassiopeia.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Made with Avalonia.
        /// </summary>
        public static string about1 {
            get {
                return ResourceManager.GetString("about1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Thanks to Delunado.
        /// </summary>
        public static string about2 {
            get {
                return ResourceManager.GetString("about2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Year.
        /// </summary>
        public static string año {
            get {
                return ResourceManager.GetString("año", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Artist.
        /// </summary>
        public static string artista {
            get {
                return ResourceManager.GetString("artista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a songs.
        /// </summary>
        public static string canciones {
            get {
                return ResourceManager.GetString("canciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total duration.
        /// </summary>
        public static string dur_total {
            get {
                return ResourceManager.GetString("dur_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duration.
        /// </summary>
        public static string duracion {
            get {
                return ResourceManager.GetString("duracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genre.
        /// </summary>
        public static string genero {
            get {
                return ResourceManager.GetString("genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Black Metal.
        /// </summary>
        public static string genero_blackmetal {
            get {
                return ResourceManager.GetString("genero_blackmetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Blues rock.
        /// </summary>
        public static string genero_blues {
            get {
                return ResourceManager.GetString("genero_blues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chiptune.
        /// </summary>
        public static string genero_chiptune {
            get {
                return ResourceManager.GetString("genero_chiptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classical music.
        /// </summary>
        public static string genero_clasica {
            get {
                return ResourceManager.GetString("genero_clasica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disco.
        /// </summary>
        public static string genero_disco {
            get {
                return ResourceManager.GetString("genero_disco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Electronical music.
        /// </summary>
        public static string genero_electronica {
            get {
                return ResourceManager.GetString("genero_electronica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flamenco.
        /// </summary>
        public static string genero_flamenquito {
            get {
                return ResourceManager.GetString("genero_flamenquito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folk.
        /// </summary>
        public static string genero_folk {
            get {
                return ResourceManager.GetString("genero_folk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funk.
        /// </summary>
        public static string genero_funk {
            get {
                return ResourceManager.GetString("genero_funk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hard rock.
        /// </summary>
        public static string genero_hardrock {
            get {
                return ResourceManager.GetString("genero_hardrock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Heavy metal.
        /// </summary>
        public static string genero_heavymetal {
            get {
                return ResourceManager.GetString("genero_heavymetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indie rock.
        /// </summary>
        public static string genero_indierock {
            get {
                return ResourceManager.GetString("genero_indierock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jazz.
        /// </summary>
        public static string genero_jazz {
            get {
                return ResourceManager.GetString("genero_jazz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jazz fusion.
        /// </summary>
        public static string genero_jazz_fusion {
            get {
                return ResourceManager.GetString("genero_jazz fusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New wave.
        /// </summary>
        public static string genero_new_wave {
            get {
                return ResourceManager.GetString("genero_new wave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pop.
        /// </summary>
        public static string genero_pop {
            get {
                return ResourceManager.GetString("genero_pop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Post-punk.
        /// </summary>
        public static string genero_postpunk {
            get {
                return ResourceManager.GetString("genero_postpunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Post-rock.
        /// </summary>
        public static string genero_postrock {
            get {
                return ResourceManager.GetString("genero_postrock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progressive metal.
        /// </summary>
        public static string genero_progmetal {
            get {
                return ResourceManager.GetString("genero_progmetal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punk.
        /// </summary>
        public static string genero_punk {
            get {
                return ResourceManager.GetString("genero_punk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progressive rock.
        /// </summary>
        public static string genero_rockprog {
            get {
                return ResourceManager.GetString("genero_rockprog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Psychedellic rock.
        /// </summary>
        public static string genero_rockpsicodelico {
            get {
                return ResourceManager.GetString("genero_rockpsicodelico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Symphonic Rock.
        /// </summary>
        public static string genero_rocksinfonico {
            get {
                return ResourceManager.GetString("genero_rocksinfonico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ska.
        /// </summary>
        public static string genero_ska {
            get {
                return ResourceManager.GetString("genero_ska", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stoner.
        /// </summary>
        public static string genero_stoner {
            get {
                return ResourceManager.GetString("genero_stoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stoner rock/metal.
        /// </summary>
        public static string genero_vaporwave {
            get {
                return ResourceManager.GetString("genero_vaporwave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        public static string menu_archivo {
            get {
                return ResourceManager.GetString("menu_archivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This Spotify account is not Premium, you will not be able to use Spotify from Cassiopeiar..
        /// </summary>
        public static string noPremium {
            get {
                return ResourceManager.GetString("noPremium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit.
        /// </summary>
        public static string salir {
            get {
                return ResourceManager.GetString("salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search....
        /// </summary>
        public static string search_help {
            get {
                return ResourceManager.GetString("search_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
    }
}
